# Generated by Django 5.1.1 on 2024-09-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='uploads/')),
                ('files', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default=None, max_length=100, null=True)),
                ('class_name', models.CharField(default=None, max_length=100, null=True)),
                ('number', models.CharField(default=None, max_length=100, null=True)),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('sex', models.CharField(max_length=10)),
                ('attitude', models.CharField(default=None, max_length=100, null=True)),
                ('skill', models.CharField(default=None, max_length=100, null=True)),
                ('friendship', models.CharField(default=None, max_length=100, null=True)),
                ('minusclass', models.CharField(default=None, max_length=100, null=True)),
                ('minusname', models.CharField(default=None, max_length=100, null=True)),
                ('plusclass', models.CharField(default=None, max_length=100, null=True)),
                ('plusname', models.CharField(default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
